server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Thiagojs11/microservices-repo
          search-paths: fornecedor
          default-label: main

